### ISSUE TITLE
one question on Seq2Seq model architecture 

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [ekinakyurek/lexical#1]
Hi, Akyurek!
    Thanks for your impressive work 'lexicon learning...' and opening source its code. I want to know that can I reproduce the results of geca (on the paper of 'Lexicon learning for few-shot Neural Seq Modeling') with the LSTM-hyper-params in this repo?  I noticed that the results of geca(100% for jump, 99.8% for around.right.) is initially reported in your previous paper'Learning to R&R...'. Are you just citing the above results from that paper? Or we can use the LSTM-hyper-params in this repo to reproduce those?
    I'd appreciate it if getting reply from you : )

**Comment by ekinakyurek** [comment]
Hi @Joeylee-rio,

I am sorry that I didn't see this earlier. Yes, we ended up with better hyper-parameters by chance. I was replicating the experiments in GECA and entered the augmentation ratio differently by mistake. And it worked better. Thus, we report the best results in R&R paper.

**Comment by Zhaoyi-Li21** [comment]
> Hi @Joeylee-rio,
> 
> I am sorry that I didn't see this earlier. Yes, we ended up with better hyper-parameters by chance. I was replicating the experiments in GECA and entered the augmentation ratio differently by mistake. And it worked better. Thus, we report the best results in R&R paper.

Hi, Akyurek, thanks a lot for replying.
So the augmentation ratio is the `key hyper-parameter` ? That's kind of intreseting to me :)
For SCAN-around right split, I tuned the aug_ratios in {0.3, 0.4, 0.5} , the LSTM-archs in {one-layer and bidirection, two-layer and bidirection} , and embedding size in {64, 512}. And **the best performance I got is around 84%**(compared with results I reported in the original GECA paper: **82%**).

I also checked the error cases and most of the cases my models did not solved are similar to some extent : 
e.g., 
**errorcase1:** turn around right thirce after walk opposite left twice, 
**errorcase2:** look around left thirce and run around right twice.

That is, when the lex `left` and phrase `around right` co-occur, it seems hard for models to solve these examples.
Reason: when we use GECA algorithm to augment, we would substitute **all of** the **_'left' ,'I_TURN_LEFT'_** pairs with **_'right', 'I_TURN_RIGHT'_** pairs **at the same time**, so the augmented set does not cover the above examples (which contain both of **_left_** and **_around right_** in them.)

My point is that seems this question is not supposed to be attributed to the 'aug_ratio' hyperparam, Could you please leave some suggestions for me to reproduce 99.8% on SCAN-around right split with GECA ? 
Or  Could you please leave a hyperparam-list ( geca_aug_num, aug_ratio, 1-layer LSTM or 2-layer LSTM, bidirectional or not, embedding size, ... ) for me to double-check? 

Appreciate!!!

**Comment by ekinakyurek** [comment]
Have you seen the repo from that I obtained these results?

https://github.com/ekinakyurek/compgen

**Comment by ekinakyurek** [comment]
But I see what you mean. I would be happy to look into this more online. Can you email me akyurekekin@gmail.com to find a time?

**Comment by Zhaoyi-Li21** [comment]
ofcourse：）

**Comment by Zhaoyi-Li21** [comment]
> Have you seen the repo from that I obtained these results?
> 
> https://github.com/ekinakyurek/compgen

Yep, I 've seen that repo but forgive me that I did not find the detailed hyperparams for `geca` ：）
